/** All option files that belong to the current behavior have to be included by this file. */

#include "Options/Soccer.h"

#include "Options/GameControl/HandleGameState.h"
#include "Options/GameControl/HandlePenaltyState.h"
#include "Options/GameControl/PlayingState.h"
#include "Options/GameControl/ReadyState.h"
#include "Options/GameControl/BDefenderReadyState.h"
#include "Options/GameControl/FDefenderReadyState.h"
#include "Options/GameControl/CBDefenderReadyState.h"
#include "Options/GameControl/CFDefenderReadyState.h"
#include "Options/GameControl/KDefenderReadyState.h"
#include "Options/GameControl/TextRobotFDefenderReadyState.h"
#include "Options/GameControl/TextRobotBDefenderReadyState.h"
#include "Options/HeadControl/LookForward.h"
#include "Options/HeadControl/LookLeftAndRight.h"
#include "Options/HeadControl/FollowTheTarget.h"

#include "Options/Output/Activity.h"
#include "Options/Output/Annotation.h"
#include "Options/Output/HeadControlMode.h"
#include "Options/Output/HeadMotionRequest/SetHeadPanTilt.h"
#include "Options/Output/HeadMotionRequest/SetHeadTarget.h"
#include "Options/Output/HeadMotionRequest/SetHeadTargetOnGround.h"
#include "Options/Output/MotionRequest/InWalkKick.h"
#include "Options/Output/MotionRequest/SpecialAction.h"
#include "Options/Output/MotionRequest/Stand.h"
#include "Options/Output/MotionRequest/WalkAtAbsoluteSpeed.h"
#include "Options/Output/MotionRequest/WalkAtRelativeSpeed.h"
#include "Options/Output/MotionRequest/WalkToTarget.h"
#include "Options/Output/MotionRequest/GetUpEngine.h"
#include "Options/Output/PlaySound.h"
#include "Options/Output/MotionRequest/Shoot.h"

//#include "Options/Output/MotionRequest/KickToPoint.h"

#include "Options/Roles/GoalFreeKick.h"
#include "Options/Roles/CStriker.h"
#include "Options/Roles/Striker.h"
#include "Options/Roles/KDefender.h"
#include "Options/Roles/BDefender.h"
#include "Options/Roles/BDefender1.h"
#include "Options/Roles/CBDefender.h"
#include "Options/Roles/FDefender.h"
#include "Options/Roles/FDefender1.h"
#include "Options/Roles/CFDefender.h"
#include "Options/Roles/Keeper.h"
#include "Options/Roles/TestRobot.h"
#include "Options/Roles/TextRobotFDefender.h"
#include "Options/Roles/TextRobotBDefender.h"
#include "Options/Skills/GetUp.h"

#include "Options/Tools/ButtonPressedAndReleased.h"
#include "Options/Tools/USBCheck.h"

